/* global window */
"use strict";

window.EMOJI_COMPLETER_DATA = [
  { emoji: "😀", shortcode: "grinning", aliases: ["smile"], keywords: ["face", "happy"] },
  { emoji: "😁", shortcode: "grin", aliases: [], keywords: ["face", "happy"] },
  { emoji: "😂", shortcode: "joy", aliases: ["tears_of_joy"], keywords: ["face", "laugh", "cry"] },
  { emoji: "🤣", shortcode: "rofl", aliases: ["rolling_on_the_floor_laughing"], keywords: ["laugh"] },
  { emoji: "😃", shortcode: "smiley", aliases: [], keywords: ["face", "happy"] },
  { emoji: "😄", shortcode: "smile", aliases: [], keywords: ["face", "happy"] },
  { emoji: "😅", shortcode: "sweat_smile", aliases: [], keywords: ["face", "nervous"] },
  { emoji: "😆", shortcode: "laughing", aliases: ["satisfied"], keywords: ["face", "haha"] },
  { emoji: "😉", shortcode: "wink", aliases: [], keywords: ["face", "flirt"] },
  { emoji: "😊", shortcode: "blush", aliases: [], keywords: ["face", "shy"] },
  { emoji: "😇", shortcode: "innocent", aliases: [], keywords: ["angel", "halo"] },
  { emoji: "🙂", shortcode: "slight_smile", aliases: ["slightly_smiling_face"], keywords: ["face"] },
  { emoji: "🙃", shortcode: "upside_down", aliases: ["upside_down_face"], keywords: ["face"] },
  { emoji: "☺️", shortcode: "relaxed", aliases: [], keywords: ["face", "content"] },
  { emoji: "😍", shortcode: "heart_eyes", aliases: [], keywords: ["face", "love"] },
  { emoji: "😘", shortcode: "kissing_heart", aliases: [], keywords: ["face", "love"] },
  { emoji: "😗", shortcode: "kissing", aliases: [], keywords: ["face"] },
  { emoji: "🤔", shortcode: "thinking", aliases: ["thinking_face"], keywords: ["face", "hmm"] },
  { emoji: "🧐", shortcode: "monocle_face", aliases: [], keywords: ["face", "inspect"] },
  { emoji: "😐", shortcode: "neutral_face", aliases: [], keywords: ["face"] },
  { emoji: "😑", shortcode: "expressionless", aliases: [], keywords: ["face"] },
  { emoji: "😶", shortcode: "no_mouth", aliases: [], keywords: ["face"] },
  { emoji: "🙄", shortcode: "rolling_eyes", aliases: [], keywords: ["face", "eyeroll"] },
  { emoji: "😏", shortcode: "smirk", aliases: [], keywords: ["face"] },
  { emoji: "😒", shortcode: "unamused", aliases: [], keywords: ["face"] },
  { emoji: "😣", shortcode: "persevere", aliases: [], keywords: ["face", "stress"] },
  { emoji: "😞", shortcode: "disappointed", aliases: [], keywords: ["face", "sad"] },
  { emoji: "😟", shortcode: "worried", aliases: [], keywords: ["face", "sad"] },
  { emoji: "😕", shortcode: "confused", aliases: [], keywords: ["face", "huh"] },
  { emoji: "🙁", shortcode: "slightly_frowning_face", aliases: ["slight_frown"], keywords: ["face", "sad"] },
  { emoji: "☹️", shortcode: "frowning_face", aliases: ["frowning2"], keywords: ["face", "sad"] },
  { emoji: "😮", shortcode: "open_mouth", aliases: [], keywords: ["face", "surprised"] },
  { emoji: "😯", shortcode: "hushed", aliases: [], keywords: ["face", "surprised"] },
  { emoji: "😲", shortcode: "astonished", aliases: [], keywords: ["face", "wow"] },
  { emoji: "😳", shortcode: "flushed", aliases: [], keywords: ["face", "blush"] },
  { emoji: "🥺", shortcode: "pleading_face", aliases: ["pleading"], keywords: ["face", "beg"] },
  { emoji: "😢", shortcode: "cry", aliases: [], keywords: ["face", "sad"] },
  { emoji: "😭", shortcode: "sob", aliases: [], keywords: ["face", "crying"] },
  { emoji: "😱", shortcode: "scream", aliases: [], keywords: ["face", "shock"] },
  { emoji: "😠", shortcode: "angry", aliases: [], keywords: ["face", "mad"] },
  { emoji: "😡", shortcode: "rage", aliases: ["pouting_face"], keywords: ["face", "mad"] },
  { emoji: "😤", shortcode: "triumph", aliases: [], keywords: ["face", "steam"] },
  { emoji: "😴", shortcode: "sleeping", aliases: [], keywords: ["face", "tired"] },
  { emoji: "😪", shortcode: "sleepy", aliases: [], keywords: ["face", "tired"] },
  { emoji: "🥱", shortcode: "yawning_face", aliases: ["yawn"], keywords: ["face", "tired"] },
  { emoji: "😷", shortcode: "mask", aliases: [], keywords: ["sick"] },
  { emoji: "🤒", shortcode: "thermometer_face", aliases: [], keywords: ["sick"] },
  { emoji: "🤕", shortcode: "face_with_head_bandage", aliases: ["head_bandage"], keywords: ["hurt"] },
  { emoji: "🤢", shortcode: "nauseated_face", aliases: ["nauseated"], keywords: ["sick"] },
  { emoji: "🤮", shortcode: "vomiting_face", aliases: ["puke"], keywords: ["sick"] },
  { emoji: "🤯", shortcode: "exploding_head", aliases: ["mind_blown"], keywords: ["shock"] },
  { emoji: "🤠", shortcode: "cowboy_hat_face", aliases: ["cowboy"], keywords: ["hat"] },
  { emoji: "🥳", shortcode: "partying_face", aliases: ["partying"], keywords: ["celebrate"] },
  { emoji: "🤗", shortcode: "hugging_face", aliases: ["hugging"], keywords: ["hug"] },
  { emoji: "🫠", shortcode: "melting_face", aliases: ["melting"], keywords: ["awkward"] },
  { emoji: "🫡", shortcode: "saluting_face", aliases: ["salute"], keywords: ["respect"] },
  { emoji: "😎", shortcode: "sunglasses", aliases: [], keywords: ["cool"] },
  { emoji: "🤓", shortcode: "nerd_face", aliases: ["nerd"], keywords: ["glasses"] },
  { emoji: "🤡", shortcode: "clown_face", aliases: ["clown"], keywords: ["circus"] },
  { emoji: "💩", shortcode: "poop", aliases: ["pile_of_poo"], keywords: ["shit"] },
  { emoji: "💀", shortcode: "skull", aliases: [], keywords: ["dead"] },
  { emoji: "☠️", shortcode: "skull_crossbones", aliases: [], keywords: ["danger"] },
  { emoji: "👻", shortcode: "ghost", aliases: [], keywords: ["halloween"] },
  { emoji: "👽", shortcode: "alien", aliases: [], keywords: ["ufo"] },
  { emoji: "🤖", shortcode: "robot", aliases: ["robot_face"], keywords: ["bot"] },
  { emoji: "❤️", shortcode: "heart", aliases: ["red_heart"], keywords: ["love"] },
  { emoji: "🧡", shortcode: "orange_heart", aliases: [], keywords: ["love"] },
  { emoji: "💛", shortcode: "yellow_heart", aliases: [], keywords: ["love"] },
  { emoji: "💚", shortcode: "green_heart", aliases: [], keywords: ["love"] },
  { emoji: "💙", shortcode: "blue_heart", aliases: [], keywords: ["love"] },
  { emoji: "💜", shortcode: "purple_heart", aliases: [], keywords: ["love"] },
  { emoji: "🖤", shortcode: "black_heart", aliases: [], keywords: ["love"] },
  { emoji: "🤍", shortcode: "white_heart", aliases: [], keywords: ["love"] },
  { emoji: "🤎", shortcode: "brown_heart", aliases: [], keywords: ["love"] },
  { emoji: "💔", shortcode: "broken_heart", aliases: [], keywords: ["sad", "love"] },
  { emoji: "💖", shortcode: "sparkling_heart", aliases: [], keywords: ["love"] },
  { emoji: "💕", shortcode: "two_hearts", aliases: [], keywords: ["love"] },
  { emoji: "💞", shortcode: "revolving_hearts", aliases: [], keywords: ["love"] },
  { emoji: "💓", shortcode: "heartbeat", aliases: [], keywords: ["love"] },
  { emoji: "💗", shortcode: "heartpulse", aliases: [], keywords: ["love"] },
  { emoji: "💝", shortcode: "gift_heart", aliases: [], keywords: ["love"] },
  { emoji: "❤️‍🔥", shortcode: "heart_on_fire", aliases: ["fire_heart"], keywords: ["love"] },
  { emoji: "🔥", shortcode: "fire", aliases: [], keywords: ["lit", "hot"] },
  { emoji: "✨", shortcode: "sparkles", aliases: [], keywords: ["star"] },
  { emoji: "⭐", shortcode: "star", aliases: [], keywords: ["favorite"] },
  { emoji: "🌟", shortcode: "star2", aliases: [], keywords: ["glow"] },
  { emoji: "💫", shortcode: "dizzy", aliases: [], keywords: ["sparkle"] },
  { emoji: "💥", shortcode: "boom", aliases: ["collision"], keywords: ["explode"] },
  { emoji: "⚡", shortcode: "zap", aliases: [], keywords: ["electric"] },
  { emoji: "☀️", shortcode: "sunny", aliases: ["sun"], keywords: ["weather"] },
  { emoji: "🌙", shortcode: "crescent_moon", aliases: ["moon"], keywords: ["night"] },
  { emoji: "☁️", shortcode: "cloud", aliases: [], keywords: ["weather"] },
  { emoji: "🌧️", shortcode: "rain_cloud", aliases: ["rain"], keywords: ["weather"] },
  { emoji: "❄️", shortcode: "snowflake", aliases: [], keywords: ["winter"] },
  { emoji: "🌈", shortcode: "rainbow", aliases: [], keywords: ["weather"] },
  { emoji: "👍", shortcode: "thumbsup", aliases: ["+1", "thumbs_up"], keywords: ["approve"] },
  { emoji: "👎", shortcode: "thumbsdown", aliases: ["-1", "thumbs_down"], keywords: ["disapprove"] },
  { emoji: "👏", shortcode: "clap", aliases: [], keywords: ["applause"] },
  { emoji: "🙏", shortcode: "pray", aliases: ["folded_hands"], keywords: ["please", "thanks"] },
  { emoji: "🙌", shortcode: "raised_hands", aliases: [], keywords: ["celebrate"] },
  { emoji: "💪", shortcode: "muscle", aliases: [], keywords: ["strong"] },
  { emoji: "👋", shortcode: "wave", aliases: [], keywords: ["hello"] },
  { emoji: "👌", shortcode: "ok_hand", aliases: [], keywords: ["ok"] },
  { emoji: "🤌", shortcode: "pinched_fingers", aliases: [], keywords: ["italian"] },
  { emoji: "🤏", shortcode: "pinching_hand", aliases: [], keywords: ["small"] },
  { emoji: "✌️", shortcode: "v", aliases: ["peace"], keywords: ["victory"] },
  { emoji: "🤙", shortcode: "call_me_hand", aliases: [], keywords: ["phone"] },
  { emoji: "☝️", shortcode: "point_up", aliases: [], keywords: ["hand"] },
  { emoji: "👇", shortcode: "point_down", aliases: [], keywords: ["hand"] },
  { emoji: "👈", shortcode: "point_left", aliases: [], keywords: ["hand"] },
  { emoji: "👉", shortcode: "point_right", aliases: [], keywords: ["hand"] },
  { emoji: "👆", shortcode: "point_up_2", aliases: [], keywords: ["hand"] },
  { emoji: "🤝", shortcode: "handshake", aliases: [], keywords: ["deal"] },
  { emoji: "✍️", shortcode: "writing_hand", aliases: [], keywords: ["write"] },
  { emoji: "🤞", shortcode: "crossed_fingers", aliases: [], keywords: ["luck"] },
  { emoji: "🤟", shortcode: "love_you_gesture", aliases: ["ily_hand"], keywords: ["love"] },
  { emoji: "🤘", shortcode: "metal", aliases: ["sign_of_the_horns"], keywords: ["rock"] },
  { emoji: "💅", shortcode: "nail_care", aliases: [], keywords: ["sass"] },
  { emoji: "💯", shortcode: "100", aliases: [], keywords: ["score"] },
  { emoji: "✅", shortcode: "white_check_mark", aliases: ["check"], keywords: ["done"] },
  { emoji: "✔️", shortcode: "heavy_check_mark", aliases: [], keywords: ["done"] },
  { emoji: "❌", shortcode: "x", aliases: ["cross_mark"], keywords: ["cancel"] },
  { emoji: "⚠️", shortcode: "warning", aliases: [], keywords: ["alert"] },
  { emoji: "⛔", shortcode: "no_entry", aliases: [], keywords: ["forbidden"] },
  { emoji: "🚫", shortcode: "prohibited", aliases: [], keywords: ["forbidden"] },
  { emoji: "❓", shortcode: "question", aliases: [], keywords: ["confused"] },
  { emoji: "❗", shortcode: "exclamation", aliases: ["heavy_exclamation_mark"], keywords: ["important"] },
  { emoji: "⁉️", shortcode: "interrobang", aliases: [], keywords: ["question"] },
  { emoji: "💬", shortcode: "speech_balloon", aliases: [], keywords: ["chat"] },
  { emoji: "💭", shortcode: "thought_balloon", aliases: [], keywords: ["thinking"] },
  { emoji: "👀", shortcode: "eyes", aliases: [], keywords: ["look"] },
  { emoji: "🧠", shortcode: "brain", aliases: [], keywords: ["smart"] },
  { emoji: "🚀", shortcode: "rocket", aliases: [], keywords: ["launch"] },
  { emoji: "💻", shortcode: "computer", aliases: ["laptop"], keywords: ["tech"] },
  { emoji: "📱", shortcode: "iphone", aliases: ["mobile_phone"], keywords: ["phone"] },
  { emoji: "⌨️", shortcode: "keyboard", aliases: [], keywords: ["type"] },
  { emoji: "🎧", shortcode: "headphones", aliases: [], keywords: ["music"] },
  { emoji: "🎤", shortcode: "microphone", aliases: ["mic"], keywords: ["audio"] },
  { emoji: "📷", shortcode: "camera", aliases: [], keywords: ["photo"] },
  { emoji: "🎥", shortcode: "movie_camera", aliases: ["camera_video"], keywords: ["video"] },
  { emoji: "🔊", shortcode: "loud_sound", aliases: ["speaker"], keywords: ["volume"] },
  { emoji: "🔇", shortcode: "mute", aliases: [], keywords: ["silent"] },
  { emoji: "🔔", shortcode: "bell", aliases: [], keywords: ["notification"] },
  { emoji: "🔕", shortcode: "no_bell", aliases: [], keywords: ["silent"] },
  { emoji: "🔒", shortcode: "lock", aliases: [], keywords: ["secure"] },
  { emoji: "🔓", shortcode: "unlock", aliases: [], keywords: ["open"] },
  { emoji: "🔑", shortcode: "key", aliases: [], keywords: ["password"] },
  { emoji: "🔨", shortcode: "hammer", aliases: [], keywords: ["tool"] },
  { emoji: "🔧", shortcode: "wrench", aliases: [], keywords: ["tool"] },
  { emoji: "⚙️", shortcode: "gear", aliases: [], keywords: ["settings"] },
  { emoji: "🧰", shortcode: "toolbox", aliases: [], keywords: ["tool"] },
  { emoji: "🔎", shortcode: "mag_right", aliases: ["search"], keywords: ["find"] },
  { emoji: "💰", shortcode: "moneybag", aliases: [], keywords: ["cash"] },
  { emoji: "🪙", shortcode: "coin", aliases: [], keywords: ["money"] },
  { emoji: "💳", shortcode: "credit_card", aliases: [], keywords: ["pay"] },
  { emoji: "💎", shortcode: "gem", aliases: [], keywords: ["diamond"] },
  { emoji: "🍕", shortcode: "pizza", aliases: [], keywords: ["food"] },
  { emoji: "🍔", shortcode: "hamburger", aliases: ["burger"], keywords: ["food"] },
  { emoji: "🍟", shortcode: "fries", aliases: [], keywords: ["food"] },
  { emoji: "🌭", shortcode: "hotdog", aliases: [], keywords: ["food"] },
  { emoji: "🌮", shortcode: "taco", aliases: [], keywords: ["food"] },
  { emoji: "🌯", shortcode: "burrito", aliases: [], keywords: ["food"] },
  { emoji: "🥪", shortcode: "sandwich", aliases: [], keywords: ["food"] },
  { emoji: "🍜", shortcode: "ramen", aliases: [], keywords: ["food"] },
  { emoji: "🍝", shortcode: "spaghetti", aliases: [], keywords: ["food"] },
  { emoji: "🍣", shortcode: "sushi", aliases: [], keywords: ["food"] },
  { emoji: "☕", shortcode: "coffee", aliases: [], keywords: ["drink"] },
  { emoji: "🍵", shortcode: "tea", aliases: [], keywords: ["drink"] },
  { emoji: "🍺", shortcode: "beer", aliases: [], keywords: ["drink"] },
  { emoji: "🍻", shortcode: "beers", aliases: [], keywords: ["drink"] },
  { emoji: "🍷", shortcode: "wine_glass", aliases: ["wine"], keywords: ["drink"] },
  { emoji: "🍸", shortcode: "cocktail", aliases: [], keywords: ["drink"] },
  { emoji: "🍹", shortcode: "tropical_drink", aliases: [], keywords: ["drink"] },
  { emoji: "🍾", shortcode: "champagne", aliases: ["bottle_with_popping_cork"], keywords: ["celebrate"] },
  { emoji: "🎂", shortcode: "birthday", aliases: ["cake"], keywords: ["celebrate"] },
  { emoji: "🧁", shortcode: "cupcake", aliases: [], keywords: ["dessert"] },
  { emoji: "🍪", shortcode: "cookie", aliases: [], keywords: ["dessert"] },
  { emoji: "🍿", shortcode: "popcorn", aliases: [], keywords: ["snack"] },
  { emoji: "🍎", shortcode: "apple", aliases: [], keywords: ["fruit"] },
  { emoji: "🍌", shortcode: "banana", aliases: [], keywords: ["fruit"] },
  { emoji: "🍇", shortcode: "grapes", aliases: [], keywords: ["fruit"] },
  { emoji: "🍉", shortcode: "watermelon", aliases: [], keywords: ["fruit"] },
  { emoji: "🍓", shortcode: "strawberry", aliases: [], keywords: ["fruit"] },
  { emoji: "🍒", shortcode: "cherries", aliases: [], keywords: ["fruit"] },
  { emoji: "🍑", shortcode: "peach", aliases: [], keywords: ["fruit"] },
  { emoji: "🍍", shortcode: "pineapple", aliases: [], keywords: ["fruit"] },
  { emoji: "🐶", shortcode: "dog", aliases: ["dog_face"], keywords: ["animal"] },
  { emoji: "🐱", shortcode: "cat", aliases: ["cat_face"], keywords: ["animal"] },
  { emoji: "🐭", shortcode: "mouse", aliases: [], keywords: ["animal"] },
  { emoji: "🐹", shortcode: "hamster", aliases: [], keywords: ["animal"] },
  { emoji: "🐰", shortcode: "rabbit", aliases: ["bunny"], keywords: ["animal"] },
  { emoji: "🦊", shortcode: "fox", aliases: [], keywords: ["animal"] },
  { emoji: "🐻", shortcode: "bear", aliases: [], keywords: ["animal"] },
  { emoji: "🐼", shortcode: "panda_face", aliases: ["panda"], keywords: ["animal"] },
  { emoji: "🐨", shortcode: "koala", aliases: [], keywords: ["animal"] },
  { emoji: "🐯", shortcode: "tiger", aliases: ["tiger_face"], keywords: ["animal"] },
  { emoji: "🦁", shortcode: "lion", aliases: [], keywords: ["animal"] },
  { emoji: "🐮", shortcode: "cow", aliases: ["cow_face"], keywords: ["animal"] },
  { emoji: "🐷", shortcode: "pig", aliases: ["pig_face"], keywords: ["animal"] },
  { emoji: "🐸", shortcode: "frog", aliases: [], keywords: ["animal"] },
  { emoji: "🐵", shortcode: "monkey_face", aliases: ["monkey"], keywords: ["animal"] },
  { emoji: "🐔", shortcode: "chicken", aliases: [], keywords: ["animal"] },
  { emoji: "🐧", shortcode: "penguin", aliases: [], keywords: ["animal"] },
  { emoji: "🐦", shortcode: "bird", aliases: [], keywords: ["animal"] },
  { emoji: "🐤", shortcode: "baby_chick", aliases: [], keywords: ["animal"] },
  { emoji: "🐺", shortcode: "wolf", aliases: [], keywords: ["animal"] },
  { emoji: "🐴", shortcode: "horse", aliases: [], keywords: ["animal"] },
  { emoji: "🦄", shortcode: "unicorn", aliases: ["unicorn_face"], keywords: ["animal"] },
  { emoji: "🐝", shortcode: "bee", aliases: ["honeybee"], keywords: ["animal"] },
  { emoji: "🐛", shortcode: "bug", aliases: [], keywords: ["animal"] },
  { emoji: "🦋", shortcode: "butterfly", aliases: [], keywords: ["animal"] },
  { emoji: "🐌", shortcode: "snail", aliases: [], keywords: ["animal"] },
  { emoji: "🐟", shortcode: "fish", aliases: [], keywords: ["animal"] },
  { emoji: "🐬", shortcode: "dolphin", aliases: ["flipper"], keywords: ["animal"] },
  { emoji: "🐳", shortcode: "whale", aliases: [], keywords: ["animal"] },
  { emoji: "🦈", shortcode: "shark", aliases: [], keywords: ["animal"] },
  { emoji: "🐙", shortcode: "octopus", aliases: [], keywords: ["animal"] },
  { emoji: "🦀", shortcode: "crab", aliases: [], keywords: ["animal"] },
  { emoji: "🦞", shortcode: "lobster", aliases: [], keywords: ["animal"] },
  { emoji: "🦐", shortcode: "shrimp", aliases: [], keywords: ["animal"] },
  { emoji: "🦑", shortcode: "squid", aliases: [], keywords: ["animal"] },
  { emoji: "🐢", shortcode: "turtle", aliases: [], keywords: ["animal"] },
  { emoji: "🐍", shortcode: "snake", aliases: [], keywords: ["animal"] }
];
